services:
  - type: web
    name: braille-ocr-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata